package driver_vehicle_service.model;

import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "drivers")
public class Driver {

    @Id
    @Schema(
            description = "Unique identifier generated by MongoDB",
            accessMode = Schema.AccessMode.READ_ONLY,
            example = "6ab9f28a35e5d0b2b195e674"
    )
    private String id;

    @Schema(
            description = "Full name of the driver",
            example = "Kamal Perera"
    )
    private String name;

    @Schema(
            description = "Driver's contact phone number",
            example = "0712345678"
    )
    private String phone;

    @Schema(
            description = "Driver's license number",
            example = "B1234567"
    )
    private String licenseNumber;

    @Schema(
            description = "Current availability status of the driver",
            example = "AVAILABLE"
    )
    private String status;

    @Schema(
            description = "Geographical service area where the driver operates",
            example = "Colombo"
    )
    private String serviceArea;

    @Schema(
            description = "Simulated current latitude of the driver",
            example = "6.9271"
    )
    private Double currentLatitude;

    @Schema(
            description = "Simulated current longitude of the driver",
            example = "79.8612"
    )
    private Double currentLongitude;

    public Driver() {
    }

    public Driver(String name, String phone, String licenseNumber, String status,
                  String serviceArea, Double currentLatitude, Double currentLongitude) {
        this.name = name;
        this.phone = phone;
        this.licenseNumber = licenseNumber;
        this.status = status;
        this.serviceArea = serviceArea;
        this.currentLatitude = currentLatitude;
        this.currentLongitude = currentLongitude;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getLicenseNumber() {
        return licenseNumber;
    }

    public void setLicenseNumber(String licenseNumber) {
        this.licenseNumber = licenseNumber;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getServiceArea() {
        return serviceArea;
    }

    public void setServiceArea(String serviceArea) {
        this.serviceArea = serviceArea;
    }

    public Double getCurrentLatitude() {
        return currentLatitude;
    }

    public void setCurrentLatitude(Double currentLatitude) {
        this.currentLatitude = currentLatitude;
    }

    public Double getCurrentLongitude() {
        return currentLongitude;
    }

    public void setCurrentLongitude(Double currentLongitude) {
        this.currentLongitude = currentLongitude;
    }
}