package driver_vehicle_service.model;

import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "vehicles")
public class Vehicle {

    @Id
    @Schema(
            description = "Unique identifier generated by MongoDB",
            accessMode = Schema.AccessMode.READ_ONLY,
            example = "6ab9ff933eae7f2428c13b85"
    )
    private String id;

    @Schema(
            description = "Vehicle registration/identification number",
            example = "CAB-1234"
    )
    private String vehicleNumber;

    @Schema(
            description = "Type of vehicle",
            example = "CAR"
    )
    private String type;

    @Schema(
            description = "Vehicle model",
            example = "Toyota Prius"
    )
    private String model;

    @Schema(
            description = "Vehicle color",
            example = "White"
    )
    private String color;

    @Schema(
            description = "Current availability status of the vehicle",
            example = "AVAILABLE"
    )
    private String status;

    public Vehicle() {
    }

    public Vehicle(String vehicleNumber, String type, String model,
                   String color, String status) {
        this.vehicleNumber = vehicleNumber;
        this.type = type;
        this.model = model;
        this.color = color;
        this.status = status;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getVehicleNumber() {
        return vehicleNumber;
    }

    public void setVehicleNumber(String vehicleNumber) {
        this.vehicleNumber = vehicleNumber;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}