server.port=${PORT:8082}
spring.application.name=driver-vehicle-service


spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ridelink_driver_db}

spring.mongodb.database=${MONGODB_DATABASE:ridelink_driver_db}