server.port=8080
spring.application.name=driver-vehicle-service
spring.data.mongodb.uri=mongodb+srv://it24100061_db_user:8ANcb0yJmKfqwKRP@clusterridelink.dgz55zm.mongodb.net/driver_vehicle_db?appName=ClusterRideLink
