spring.application.name=driver-vehicle-service

spring.mongodb.uri=mongodb+srv://kavindugavesha36a_db_user:QkzHFzcEM7nKcVip@cluster0.bgkrq5w.mongodb.net/ridelink?appName=Cluster0

spring.mongodb.database=ridelink

server.port=8080