# Server Port (Running on 8081 so it doesn't clash with your other microservices later)
server.port=8081

# Application Name
spring.application.name=ride-management-service

spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://prarthanamaduwantha2_db_user:ZDePM2x6PI3N6Epn@cluster0ride-management.jofiz05.mongodb.net/ridelink_ride_db?appName=Cluster0ride-management-service}