
server.port=8081

# Application Name
spring.application.name=ride-management-service

spring.config.import=optional:file:.env[.properties]
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/ridelink_ride_db}