# Server Port (Running on 8081 so it doesn't clash with your other microservices later)
server.port=8081

# Application Name
spring.application.name=ride-management-service

# Database Connection (NeonDB Cloud)
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-silent-lake-b30yjunk-pooler.c-4.ap-southeast-1.aws.neon.tech/ridelink_ride_db?sslmode=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_wyW9onAEexJ5}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect