# Server Configuration
server.port=${PORT:8084}

# Application Name
spring.application.name=fare-payment-service

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ridelink_fare_db}

# JPA / Hibernate (disabled - using MongoDB)
spring.jpa.show-sql=false
# JWT Configuration
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
