# Server Configuration
server.port=8082

# Application Name
spring.application.name=fare-payment-service

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://it24100061_db_user:8ANcb0yJmKfqwKRP@clusterridelink.dgz55zm.mongodb.net/fare_payment_db?appName=ClusterRideLink

# JPA / Hibernate (disabled - using MongoDB)
spring.jpa.show-sql=false